name: KaliLinuxBuild

on:
  push:
    branches: [ main ]
    
jobs:
  build-kali:
    runs-on: ubuntu-latest
    container: 
      image: kalilinux/kali-rolling

    steps:
      - uses: actions/checkout@v2

      - name: isntall curl.... why.... why is this not default in kalis docker
        run: apt update -y && apt install gcc make cmake curl git  sqlite3 libsqlite3-dev build-essential openssl -y

      - name: Install Crystal and Shards using public installer
        run: curl -fsSL https://crystal-lang.org/install.sh | bash

      - name: Install shard dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Install shard dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Build Project
        run: crystal build src/spraycannon.cr --release

      - name: Bulid Project 2
        run: crystal build src/spdb.cr --release
