name: StaticLinuxBuild

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**'

jobs:
  build-static:
    runs-on: ubuntu-latest
    container: 
      image: crystallang/crystal:latest-alpine
    
    steps:
      - uses: actions/checkout@v2

      - name: install dependancies for alpine 
        run: apk update -y && apk add gcc make cmake git sqlite 

      - name: Install shard dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Build Project
        run: crystal build src/spraycannon.cr --release -p 

      - name: Bulid Project 2
        run: crystal build src/spdb.cr --release -p 